ALTER TABLE sessions ADD COLUMN event VARCHAR(16) NOT NULL DEFAULT '333';
ALTER TABLE sessions ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE solves ADD COLUMN penalty VARCHAR(16) NOT NULL DEFAULT 'NONE';